// Purpose: Verify append-only versions, per-question caching, replay, statistics, budgets, timelines and offline HTML.
import test from 'node:test';import assert from 'node:assert/strict';import { mkdtemp,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';import { importItems,readCorpus,runPolicy,diffPolicies,whatIf,sweep,timeline,mcnemarExact,wilson,htmlReport,judgmentKey } from '../src/index.mjs';import { createFakeProvider } from '../src/jev-client.mjs';
const policy=(version='1',instruction='Urgent?',threshold=.8)=>({schemaVersion:1,name:'x',version,description:'x',model:'jev-1.13.0',inputs:{text:'string'},questions:{urgent:{type:'noul',instructions:instruction}},rules:[{id:'r',outcome:'review',all:[{field:'answers.urgent.noul',op:'gte',value:threshold}]}],fallback:'accept'});
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'time-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));await importItems(dir,[{id:'a',text:'urgent',occurred_at:'2025-12-31'},{id:'b',text:'fine',occurred_at:'2026-01-01'}]);return dir;}
test('import is idempotent and changed text is a new version',async t=>{const d=await fixture(t);assert.deepEqual((await importItems(d,[{id:'a',text:'urgent',occurred_at:'2025-12-31'}])).unchanged,1);await importItems(d,[{id:'a',text:'changed',occurred_at:'2025-12-31'}]);assert.equal((await readCorpus(d)).length,3)});
test('cache is stable and diff buys only a changed question',async t=>{const d=await fixture(t),p=createFakeProvider((s)=>({type:'noul',noul:s.text==='urgent'?.9:.1}));const a=await runPolicy(d,policy(),{provider:p});assert.equal(a.boughtJudgments,2);const again=await runPolicy(d,policy('2'),{provider:p});assert.equal(again.boughtJudgments,0);const diff=await diffPolicies(d,policy(),policy('3','Needs immediate attention?'),{provider:p});assert.equal(diff.after.boughtJudgments,2);assert.equal(p.calls.length,4)});
test('whatif is provider-free and sweep is monotone',async t=>{const d=await fixture(t),p=createFakeProvider(s=>({type:'noul',noul:s.text==='urgent'?.9:.1}));const run=await runPolicy(d,policy(),{provider:p}),calls=p.calls.length;assert.deepEqual(whatIf(policy(),run,{urgent:.95}).map(x=>x.after),['accept','accept']);const rows=sweep(policy(),run,'urgent',.5,.95,.15);assert.deepEqual(rows.map(r=>r.outcomes.review??0),[1,1,1,0]);assert.equal(p.calls.length,calls)});
test('budget stops cleanly and resume uses bought work',async t=>{const d=await fixture(t),p=createFakeProvider(()=>({type:'noul',noul:.9}));const stopped=await runPolicy(d,policy(),{provider:p,budgetUsd:.00000001});assert.equal(stopped.stoppedForBudget,true);const done=await runPolicy(d,policy(),{provider:p,budgetUsd:1});assert.equal(done.itemCount,2)});
test('timeline crosses month and year and statistics match known values',async t=>{const d=await fixture(t),p=createFakeProvider(()=>({type:'noul',noul:.9})),run=await runPolicy(d,policy(),{provider:p});assert.deepEqual(Object.keys(timeline(run)),['2025-12','2026-01']);assert.equal(mcnemarExact(1,3).pValue,.625);assert.ok(Math.abs(wilson(5,10).low-.2366)<.001)});
test('cache key is symmetric only in its exact inputs and HTML is offline',()=>{assert.equal(judgmentKey('m','q',{type:'noul',instructions:'x'},'h'),judgmentKey('m','q',{instructions:'x',type:'noul'},'h'));const html=htmlReport({ok:true});assert.match(html,/<!doctype html>/);assert.doesNotMatch(html,/https?:\/\//)});
