// Purpose: Hand-written public declarations for jev-timemachine.
export type Question = { type: 'noul'|'choice'|'score'; instructions: string; criteria?: unknown };
export interface Item { id: string; occurredAt: string; text: string; meta: Record<string, unknown>; hash: string }
export interface Policy { schemaVersion: 1; name: string; version: string; description: string; model: 'jev-1.13.0'; inputs: Record<string,string>; questions: Record<string,Question>; rules: Array<{id:string;outcome:string;all:Array<{field:string;op:string;value:unknown}>}>; fallback:string }
export interface Provider { (request:{model:string;state:unknown;questions:Record<string,Question>;signal?:AbortSignal}):Promise<any>; calls?: unknown[] }
export declare const MODEL: string; export declare const PRICE: number;
export declare function canonicalJson(value:unknown):string; export declare function sha256(value:unknown):string; export declare function estimateTokens(value:unknown):number; export declare function estimateCostUsd(tokens:number):number;
export declare function validatePolicy(pack:Policy):Policy; export declare function policyFingerprint(pack:Policy):string; export declare function questionFingerprint(model:string,id:string,question:Question):string; export declare function judgmentKey(model:string,id:string,question:Question,itemHash:string):string;
export declare function decide(pack:Policy,item:Item,answers:Record<string,unknown>):{outcome:string;ruleId:string|null};
export declare function normalizeItem(row:Record<string,unknown>,mapping?:{id?:string;text?:string;time?:string;meta?:string[]}):Item;
export declare function importItems(store:string,rows:Record<string,unknown>[],mapping?:object):Promise<{added:number;unchanged:number;items:Item[]}>; export declare function readCorpus(store:string):Promise<Item[]>; export declare function sliceItems(items:Item[],range?:{from?:string;to?:string}):Item[];
export declare function estimateRun(store:string,pack:Policy,range?:object):Promise<any>; export declare function runPolicy(store:string,pack:Policy,options:{provider:Provider;budgetUsd?:number;from?:string;to?:string}):Promise<any>; export declare function diffPolicies(store:string,before:Policy,after:Policy,options:any):Promise<any>;
export declare function withThresholds(pack:Policy,overrides:Record<string,number>):Policy; export declare function whatIf(pack:Policy,run:any,overrides:Record<string,number>):any[]; export declare function sweep(pack:Policy,run:any,questionId:string,start:number,stop:number,step:number):any[]; export declare function timeline(run:any,bucket?:'month'|'year'):Record<string,Record<string,number>>;
export declare function wilson(successes:number,n:number,z?:number):{estimate:number|null;low:number;high:number}; export declare function mcnemarExact(b:number,c:number):{b:number;c:number;pValue:number}; export declare function comparePolicies(a:any,b:any,labels:Record<string,string>):any; export declare function htmlReport(data:unknown):string;
export declare function createJevClient(options?:object):Provider; export declare function createFakeProvider(resolve:(state:any,id:string,question:Question)=>any):Provider & {calls:unknown[]};
